# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e298c46f441578735f8c2fb971e262e"
name = "Central Chats"
application_url = "https://suit-docs-sponsor-feet.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_script_tags,write_script_tags"

[auth]
redirect_urls = [ "https://suit-docs-sponsor-feet.trycloudflare.com/api/auth/callback"]
